# Copyright (c) 2023-2026 Christiaan (chris@boreddev.nl)
# This software is released under the GNU General Public License v3.0. See LICENSE file for details.
# This header needs to maintain in any file it is present in, as per the GPL license terms.
#
#
# index.toml, this get's pushed towards bur.boredos.dev and the bpm client will be able to parse this to download the .bup files.
[package.nova]
name = "nova"
version = "1.2"
description = "Nova compositor and supporting daemons"
author = "BoredOS Official"
license = "GPLv3"
url = "https://github.com/BoredOS/nova/releases/download/1.2/nova-1.2.bup"
sha256 = "5dca4d85da9dd379950cf68d179c8a46ad2b56d4f018fa632b70588541229854"

[package.colloidicons]
name = "colloidicons"
version = "1.0"
description = "A PNG-only version of the colloid icon pack."
author = "vinceliuice"
license = "GPLv3"
url = "https://github.com/BoredOS/colloid/releases/download/1.0/colloidicons-1.0.bup"
sha256 = "20d4a12b3d0977672ef6ca3334a255b8b01b11b89a68e02e5231740d8b613e08"
